### ISSUE TITLE
Exo.Spine.Stack

### ISSUE THREAD

**Issue by raedatoui** [jpettersson/exo.js#8]
i would like to hear your opinion. wouldn't it be useful if we added animations to the Stack's behavior?

**Comment by jpettersson** [comment]
It's a tricky one.. as of right now it's kind of possible to do animations, but only if they run independent of each other (each controller running its own activate/deactivate transition). I've been thinking about ways of doing a more decoupled approach where the transitions are defined in the context of the Stack instead.. I'll show you my concepts in a Gist.

Do you have any suggestion of how it could work?

**Comment by raedatoui** [comment]
your idea sounds ideal, if you can define the transitions in the Stack's context. 
I looked at the stack code, and i would add the activation/deactivation of exo controllers as the routes are changing. the stack class itself doesnt need inherit from exo, but could be extended to manage exo controllers and ensure they get activated/deactivated, which by looking at the manager class code, its already doing it?
